const ROLE_IDENTIFIER = /^[a-z_][a-z0-9_]{0,62}$/;

export interface RuntimeRoleNames {
  readRole: string;
  writeRole: string;
  serviceRole: string;
}

export function validateRoleIdentifier(value: string | undefined, label: string) {
  const role = value?.trim();
  if (!role || !ROLE_IDENTIFIER.test(role) || role.startsWith("pg_")) {
    throw new Error(
      `${label} must be a lowercase PostgreSQL role identifier and must not start with pg_.`,
    );
  }
  return role;
}

function identifier(value: string) {
  return `"${value}"`;
}

export function buildRuntimeGrantsSql(roles: RuntimeRoleNames) {
  const readRole = validateRoleIdentifier(roles.readRole, "LAYPIPE_DB_READ_ROLE");
  const writeRole = validateRoleIdentifier(roles.writeRole, "LAYPIPE_DB_WRITE_ROLE");
  const serviceRole = validateRoleIdentifier(
    roles.serviceRole,
    "LAYPIPE_DB_SERVICE_ROLE",
  );
  if (new Set([readRole, writeRole, serviceRole]).size !== 3) {
    throw new Error("LayPipe database group roles must be different.");
  }
  const read = identifier(readRole);
  const write = identifier(writeRole);
  const service = identifier(serviceRole);

  return `-- Generated by scripts/indexer/runtime-grants.ts.
-- Run as the schema owner after every migration. All targets must already exist
-- as unprivileged NOLOGIN group roles; attach separate LOGIN members in Neon.
BEGIN;
SET LOCAL search_path = pg_catalog, public;

DO $laypipe_attest_roles$
DECLARE
  candidate record;
BEGIN
  FOR candidate IN
    SELECT r.rolname, r.rolsuper, r.rolinherit, r.rolcreaterole,
      r.rolcreatedb, r.rolcanlogin, r.rolreplication, r.rolbypassrls,
      EXISTS (SELECT 1 FROM pg_auth_members m WHERE m.member = r.oid) AS member_of_any,
      EXISTS (
        SELECT 1 FROM pg_auth_members m
        JOIN pg_roles member_role ON member_role.oid = m.member
        WHERE m.roleid = r.oid AND (
          r.rolname <> '${serviceRole}'
          OR member_role.rolname <> current_user
          OR NOT m.admin_option
          OR NOT m.inherit_option
          OR NOT m.set_option
        )
      ) AS has_unsafe_members,
      (SELECT count(*) FROM pg_auth_members m WHERE m.roleid = r.oid) AS member_count,
      EXISTS (SELECT 1 FROM pg_class c WHERE c.relowner = r.oid) AS owns_relation,
      EXISTS (
        SELECT 1 FROM pg_proc p
        JOIN pg_namespace n ON n.oid = p.pronamespace
        WHERE p.proowner = r.oid AND (
          r.rolname <> '${serviceRole}' OR n.nspname <> 'public'
          OR p.oid NOT IN (
            'public.laypipe_enforce_cursor_observation()'::regprocedure::oid,
            'public.laypipe_adjust_pool_market_totals()'::regprocedure::oid,
            'public.laypipe_apply_inserted_token_transfers()'::regprocedure::oid,
            'public.laypipe_apply_deleted_token_transfers()'::regprocedure::oid,
            'public.laypipe_initialize_cursor(bigint,text,bigint)'::regprocedure::oid,
            'public.laypipe_advance_cursor(bigint,text,bigint,bigint,evm_bytes32)'::regprocedure::oid,
            'public.laypipe_rollback_chain(bigint,bigint,evm_bytes32)'::regprocedure::oid,
            'public.laypipe_runtime_initialize_cursor(bigint,text,bigint)'::regprocedure::oid,
            'public.laypipe_runtime_advance_cursor(bigint,text,bigint,bigint,evm_bytes32)'::regprocedure::oid,
            'public.laypipe_runtime_record_observation(bigint,text,bigint,timestamp with time zone,text)'::regprocedure::oid,
            'public.laypipe_runtime_rollback_chain(bigint,bigint,evm_bytes32)'::regprocedure::oid
          )
        )
      ) AS owns_function,
      EXISTS (SELECT 1 FROM pg_namespace n WHERE n.nspowner = r.oid) AS owns_schema
    FROM pg_roles r
    WHERE r.rolname IN ('${readRole}', '${writeRole}', '${serviceRole}')
  LOOP
    IF candidate.rolsuper OR NOT candidate.rolinherit OR candidate.rolcreaterole
       OR candidate.rolcreatedb OR candidate.rolcanlogin OR candidate.rolreplication
       OR candidate.rolbypassrls OR candidate.member_of_any
       OR (candidate.rolname = '${serviceRole}' AND (
         candidate.has_unsafe_members OR candidate.member_count <> 1
       ))
       OR candidate.owns_relation
       OR candidate.owns_function OR candidate.owns_schema THEN
      RAISE EXCEPTION 'LayPipe role % failed least-privilege attestation', candidate.rolname;
    END IF;
  END LOOP;
  IF (SELECT count(*) FROM pg_roles WHERE rolname IN (
    '${readRole}', '${writeRole}', '${serviceRole}'
  )) <> 3 THEN
    RAISE EXCEPTION 'LayPipe runtime group role is missing';
  END IF;

  IF has_database_privilege('${readRole}', current_database(), 'CREATE')
     OR has_database_privilege('${writeRole}', current_database(), 'CREATE')
     OR has_database_privilege('${serviceRole}', current_database(), 'CREATE')
     OR has_schema_privilege('${readRole}', 'public', 'CREATE')
     OR has_schema_privilege('${writeRole}', 'public', 'CREATE')
     OR has_schema_privilege('${serviceRole}', 'public', 'CREATE') THEN
    RAISE EXCEPTION 'LayPipe role has ambient create privilege';
  END IF;
END
$laypipe_attest_roles$;

DO $laypipe_database_acl$
BEGIN
  EXECUTE format(
    'REVOKE TEMPORARY ON DATABASE %I FROM PUBLIC, ${read}, ${write}, ${service}',
    current_database()
  );
END
$laypipe_database_acl$;
REVOKE ALL ON SCHEMA public FROM PUBLIC;
GRANT USAGE ON SCHEMA public TO ${read}, ${write}, ${service};

REVOKE ALL ON ALL TABLES IN SCHEMA public FROM PUBLIC, ${read}, ${write}, ${service};
REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM PUBLIC, ${read}, ${write}, ${service};
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA public FROM PUBLIC, ${read}, ${write}, ${service};

GRANT SELECT ON
  laypipe_schema_migrations, laypipe_database_identity,
  chain_blocks, chain_events, indexer_cursors, launches, swaps,
  pool_market_totals, fee_events, burn_events, revenue_events,
  token_transfers, token_balances, token_holder_balance_state,
  admin_events, ipfs_promotions
TO ${read};

-- Canonical replay requires UPDATE for ON CONFLICT, but immutable triggers
-- reject changed rows. DELETE and derived-state DML remain unavailable.
GRANT SELECT, INSERT, UPDATE ON
  chain_blocks, chain_events, launches, swaps, fee_events, burn_events,
  revenue_events, token_transfers, admin_events
TO ${write};
GRANT SELECT ON
  laypipe_schema_migrations, laypipe_database_identity, indexer_cursors,
  pool_market_totals, token_holder_balance_state, token_balances
TO ${write};
GRANT SELECT, INSERT, UPDATE ON ipfs_promotions TO ${write};

-- Dedicated service ownership is the only destructive/cursor/derived-state
-- authority. It is NOLOGIN and its sole member is the migration owner with
-- ADMIN OPTION, which PostgreSQL requires to maintain service-owned functions.
GRANT CREATE ON SCHEMA public TO ${service};
ALTER FUNCTION laypipe_enforce_cursor_observation() OWNER TO ${service};
ALTER FUNCTION laypipe_adjust_pool_market_totals() OWNER TO ${service};
ALTER FUNCTION laypipe_apply_inserted_token_transfers() OWNER TO ${service};
ALTER FUNCTION laypipe_apply_deleted_token_transfers() OWNER TO ${service};
ALTER FUNCTION laypipe_initialize_cursor(bigint, text, bigint) OWNER TO ${service};
ALTER FUNCTION laypipe_advance_cursor(bigint, text, bigint, bigint, evm_bytes32) OWNER TO ${service};
ALTER FUNCTION laypipe_rollback_chain(bigint, bigint, evm_bytes32) OWNER TO ${service};
ALTER FUNCTION laypipe_runtime_initialize_cursor(bigint, text, bigint) OWNER TO ${service};
ALTER FUNCTION laypipe_runtime_advance_cursor(bigint, text, bigint, bigint, evm_bytes32) OWNER TO ${service};
ALTER FUNCTION laypipe_runtime_record_observation(bigint, text, bigint, timestamptz, text) OWNER TO ${service};
ALTER FUNCTION laypipe_runtime_rollback_chain(bigint, bigint, evm_bytes32) OWNER TO ${service};

ALTER FUNCTION laypipe_enforce_cursor_observation() SECURITY DEFINER;
ALTER FUNCTION laypipe_adjust_pool_market_totals() SECURITY DEFINER;
ALTER FUNCTION laypipe_apply_inserted_token_transfers() SECURITY DEFINER;
ALTER FUNCTION laypipe_apply_deleted_token_transfers() SECURITY DEFINER;

GRANT SELECT, INSERT, UPDATE, DELETE ON
  chain_blocks, chain_events, launches, swaps, fee_events, burn_events,
  revenue_events, token_transfers, admin_events, indexer_cursors,
  pool_market_totals, token_holder_balance_state
TO ${service};
GRANT EXECUTE ON FUNCTION laypipe_initialize_cursor(bigint, text, bigint) TO ${service};
GRANT EXECUTE ON FUNCTION laypipe_advance_cursor(bigint, text, bigint, bigint, evm_bytes32) TO ${service};
GRANT EXECUTE ON FUNCTION laypipe_rollback_chain(bigint, bigint, evm_bytes32) TO ${service};

ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON TABLES FROM PUBLIC, ${read}, ${write}, ${service};
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON SEQUENCES FROM PUBLIC, ${read}, ${write}, ${service};
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC, ${read}, ${write}, ${service};

REVOKE EXECUTE ON ALL FUNCTIONS IN SCHEMA public FROM PUBLIC, ${read}, ${write};

GRANT EXECUTE ON FUNCTION laypipe_runtime_initialize_cursor(bigint, text, bigint) TO ${write};
GRANT EXECUTE ON FUNCTION laypipe_runtime_advance_cursor(bigint, text, bigint, bigint, evm_bytes32) TO ${write};
GRANT EXECUTE ON FUNCTION laypipe_runtime_record_observation(bigint, text, bigint, timestamptz, text) TO ${write};
GRANT EXECUTE ON FUNCTION laypipe_runtime_rollback_chain(bigint, bigint, evm_bytes32) TO ${write};

-- Pin resolution for all trigger, inner, and wrapper functions.
ALTER FUNCTION laypipe_enforce_cursor_observation() SET search_path = pg_catalog, public;
ALTER FUNCTION laypipe_adjust_pool_market_totals() SET search_path = pg_catalog, public;
ALTER FUNCTION laypipe_apply_inserted_token_transfers() SET search_path = pg_catalog, public;
ALTER FUNCTION laypipe_apply_deleted_token_transfers() SET search_path = pg_catalog, public;
ALTER FUNCTION laypipe_reject_changed_immutable_row() SET search_path = pg_catalog, public;
ALTER FUNCTION laypipe_initialize_cursor(bigint, text, bigint) SET search_path = pg_catalog, public;
ALTER FUNCTION laypipe_advance_cursor(bigint, text, bigint, bigint, evm_bytes32) SET search_path = pg_catalog, public;
ALTER FUNCTION laypipe_rollback_chain(bigint, bigint, evm_bytes32) SET search_path = pg_catalog, public;

REVOKE CREATE ON SCHEMA public FROM ${service};

DO $laypipe_attest_service_owner$
DECLARE
  service_oid oid := (SELECT oid FROM pg_roles WHERE rolname = '${serviceRole}');
BEGIN
  IF (SELECT count(*) FROM pg_auth_members WHERE roleid = service_oid) <> 1
     OR NOT EXISTS (
       SELECT 1 FROM pg_auth_members membership
       JOIN pg_roles member_role ON member_role.oid = membership.member
       WHERE membership.roleid = service_oid
         AND member_role.rolname = current_user
         AND membership.admin_option
         AND membership.inherit_option
         AND membership.set_option
     ) THEN
    RAISE EXCEPTION 'LayPipe service role operator membership is not exact';
  END IF;
  IF has_schema_privilege('${serviceRole}', 'public', 'CREATE') THEN
    RAISE EXCEPTION 'LayPipe service role retained schema create privilege';
  END IF;
  IF (SELECT count(*) FROM pg_proc WHERE proowner = service_oid) <> 11
     OR EXISTS (
       SELECT 1 FROM pg_proc p
       WHERE p.proowner = service_oid AND p.oid NOT IN (
         'public.laypipe_enforce_cursor_observation()'::regprocedure::oid,
         'public.laypipe_adjust_pool_market_totals()'::regprocedure::oid,
         'public.laypipe_apply_inserted_token_transfers()'::regprocedure::oid,
         'public.laypipe_apply_deleted_token_transfers()'::regprocedure::oid,
         'public.laypipe_initialize_cursor(bigint,text,bigint)'::regprocedure::oid,
         'public.laypipe_advance_cursor(bigint,text,bigint,bigint,evm_bytes32)'::regprocedure::oid,
         'public.laypipe_rollback_chain(bigint,bigint,evm_bytes32)'::regprocedure::oid,
         'public.laypipe_runtime_initialize_cursor(bigint,text,bigint)'::regprocedure::oid,
         'public.laypipe_runtime_advance_cursor(bigint,text,bigint,bigint,evm_bytes32)'::regprocedure::oid,
         'public.laypipe_runtime_record_observation(bigint,text,bigint,timestamp with time zone,text)'::regprocedure::oid,
         'public.laypipe_runtime_rollback_chain(bigint,bigint,evm_bytes32)'::regprocedure::oid
       )
     ) THEN
    RAISE EXCEPTION 'LayPipe service function ownership is not exact';
  END IF;
END
$laypipe_attest_service_owner$;

COMMIT;
`;
}
